# -*- coding: utf-8 -*-
"""facebook_insights_pages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbZUcnnfX8ba_gv0uRLVcYD2YPJ1A4-M
"""

import pandas as pd
from datetime import datetime, timedelta
import requests
import numpy as np

my_app_id = '846087082604504'
my_app_secret = 'be005765b88d863c474a846a8fdd7df3'
my_access_token = 'EAAMBgwAB99gBAJJYJ4X1gRchzWq8gCwfKp37lRnvd3sbX9yUaN23UpeBouS1FmYBEvLe7X4SUmeP2l8DPaPCWlTfC5iqb3eU97EoZC1rKyzwAsJ5PFZCyqMiA6uOopZAC8hM2ST5dyrtSkAqvDJhxREPGxbtHZA4ZCXEJElE4xgZDZD'

accounts_infos = requests.get('https://graph.facebook.com/v9.0/me/accounts?fields=name,username,access_token&limit=1000&access_token='+my_access_token).json()['data']
df_accounts_infos = pd.json_normalize(accounts_infos)
df_accounts_infos.rename(columns = {'name':'page_name'},inplace=True)
df_accounts_infos.rename(columns = {'id':'page_id'},inplace=True)
df_accounts_infos = df_accounts_infos.loc[df_accounts_infos['page_id'] != '442659496581990']
df_accounts_infos

start_date = '2020-11-30'
end_date = '2021-01-01'

df_values = []
insights = []
name = []
page_name = []
for page_id,access_token,page_name in zip(df_accounts_infos['page_id'],df_accounts_infos['access_token'],df_accounts_infos['page_name']):
  page_insights_infos = requests.get('https://graph.facebook.com/v9.0/'+page_id+'/insights/page_impressions_paid_unique,page_impressions_organic_unique,page_impressions_paid,page_impressions,page_impressions_viral_unique,page_impressions_viral,page_impressions_organic,page_engaged_users,page_consumptions,page_impressions_unique,page_fan_adds,page_fan_removes,page_negative_feedback/day?since=2020-12-01&until=2021-01-02&access_token='+access_token).json()

  for data_row in page_insights_infos['data']:
    name = data_row['name']
    for values in data_row['values']:
      df_values_row = pd.json_normalize(values)
      df_values_row['name'] = name
      df_values_row['page_id'] = page_id
      df_values_row['page_name'] = page_name
      df_values.append(df_values_row)

insights = pd.concat(df_values)
insights = pd.pivot_table(insights,index=['end_time','page_id','page_name'],columns='name',values='value', aggfunc=np.max, fill_value=0)
insights.reset_index(inplace=True)

for line in range(len(insights['end_time'])):
  time = insights['end_time'][line][0:10]
  date_time_obj = datetime.strptime(time, '%Y-%m-%d')
  date_time_obj = date_time_obj + timedelta(hours=-8)
  insights['end_time'][line] = date_time_obj

selected_columns = ['end_time','page_id',    'page_name','page_consumptions','page_impressions_unique','page_engaged_users','page_impressions_organic','page_impressions_paid','page_impressions_organic_unique','page_impressions_paid_unique','page_fan_adds','page_fan_removes','page_negative_feedback','page_impressions','page_impressions_viral','page_impressions_viral_unique']
column_names     = ['tempo',   'business_id','username', 'page_clicks',      'page_reach',             'page_engaged_users','page_impressions_organic','page_impressions_paid','page_reach_organic',             'page_reach_paid',             'page_fan_adds','page_fan_removes','page_negative_feedback','page_impressions','page_impressions_viral','page_reach_viral']
insights = insights[selected_columns]
insights.columns = column_names

insights.to_csv('facebook_insights_pages.csv')