# -*- coding: utf-8 -*-
"""facebook_insights_fans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AGG397mJBX86Fk-fSQVUSODRKoeKiI4c
"""

import pandas as pd
from datetime import datetime,date,timedelta
import requests
import numpy as np

my_app_id = '846087082604504'
my_app_secret = 'be005765b88d863c474a846a8fdd7df3'
my_access_token = 'EAAMBgwAB99gBAJJYJ4X1gRchzWq8gCwfKp37lRnvd3sbX9yUaN23UpeBouS1FmYBEvLe7X4SUmeP2l8DPaPCWlTfC5iqb3eU97EoZC1rKyzwAsJ5PFZCyqMiA6uOopZAC8hM2ST5dyrtSkAqvDJhxREPGxbtHZA4ZCXEJElE4xgZDZD'

sdate = date(2020,12,3)   # start date
edate = date(2021,1,3)   # end date
dates_list = pd.date_range(sdate,edate-timedelta(days=1),freq='d')
dates_list

accounts_infos = requests.get('https://graph.facebook.com/v9.0/me/accounts?fields=name,username,access_token&limit=1000&access_token='+my_access_token).json()['data']
df_accounts_infos = pd.json_normalize(accounts_infos)
df_accounts_infos.rename(columns = {'name':'page_name'},inplace=True)
df_accounts_infos.rename(columns = {'id':'page_id'},inplace=True)
df_accounts_infos = df_accounts_infos.loc[df_accounts_infos['page_id'] != '442659496581990']
df_accounts_infos['access_token'][0]

values_page_fans_country_infos = []
df_page_fans_country_values = []
values_page_fans_gender_age_infos = []
df_page_fans_gender_age_values = []
values_page_fans_city_infos = []
df_page_fans_city_values = []

for date in dates_list:
  date = str(date)[0:10]
  for page_id,page_token,username in zip(df_accounts_infos['page_id'],df_accounts_infos['access_token'],df_accounts_infos['username']):
    
    page_fans_country = requests.get('https://graph.facebook.com/v9.0/'+page_id+'/insights/page_fans_country/day?since='+date+'&until='+date+'&access_token='+page_token).json()
    for page_fans_country_row in page_fans_country['data']:
      for page_fans_country_values in page_fans_country_row['values']:
        page_fans_country_values_row = pd.json_normalize(page_fans_country_values)
        page_fans_country_values_row['page_id'] = page_id
        page_fans_country_values_row['username'] = username
        page_fans_country_values_row = page_fans_country_values_row.melt(id_vars=["end_time", "page_id","username"])
        page_fans_country_values_row['info'] = 'country'
        df_page_fans_country_values.append(page_fans_country_values_row)

    page_fans_gender_age = requests.get('https://graph.facebook.com/v9.0/'+page_id+'/insights/page_fans_gender_age/day?since='+date+'&until='+date+'&access_token='+page_token).json()
    for page_fans_gender_age_row in page_fans_gender_age['data']:
      for page_fans_gender_age_values in page_fans_gender_age_row['values']:
        page_fans_gender_age_values_row = pd.json_normalize(page_fans_gender_age_values)
        page_fans_gender_age_values_row['page_id'] = page_id
        page_fans_gender_age_values_row['username'] = username
        page_fans_gender_age_values_row = page_fans_gender_age_values_row.melt(id_vars=["end_time", "page_id","username"])
        page_fans_gender_age_values_row['info'] = 'gender_age'
        df_page_fans_gender_age_values.append(page_fans_gender_age_values_row)
    
    page_fans_city = requests.get('https://graph.facebook.com/v9.0/'+page_id+'/insights/page_fans_city/day?since='+date+'&until='+date+'&access_token='+page_token).json()
    for page_fans_city_row in page_fans_city['data']:
      for page_fans_city_values in page_fans_city_row['values']:
        page_fans_city_values_row = pd.json_normalize(page_fans_city_values)
        page_fans_city_values_row['page_id'] = page_id
        page_fans_city_values_row['username'] = username
        page_fans_city_values_row = page_fans_city_values_row.melt(id_vars=["end_time", "page_id","username"])
        page_fans_city_values_row['info'] = 'city'
        df_page_fans_city_values.append(page_fans_city_values_row)

values_page_fans_country_infos = pd.concat(df_page_fans_country_values)
values_page_fans_country_infos.columns = ['tempo','business_id','username','dimensions','fans','info']
values_page_fans_country_infos['dimensions'] = values_page_fans_country_infos['dimensions'].astype(str).str.replace('value.', '')

values_page_fans_gender_age_infos = pd.concat(df_page_fans_gender_age_values)
values_page_fans_gender_age_infos.columns = ['tempo','business_id','username','dimensions','fans','info']
values_page_fans_gender_age_infos['dimensions'] = values_page_fans_gender_age_infos['dimensions'].astype(str).str.replace('value.', '')

values_page_fans_city_infos = pd.concat(df_page_fans_city_values)
values_page_fans_city_infos.columns = ['tempo','business_id','username','dimensions','fans','info']
values_page_fans_city_infos['dimensions'] = values_page_fans_city_infos['dimensions'].astype(str).str.replace('value.', '')

partial_table_fans = values_page_fans_country_infos.append(values_page_fans_gender_age_infos)
partial_table_fans = partial_table_fans.append(values_page_fans_city_infos)
partial_table_fans.reset_index(inplace=True)
partial_table_fans.to_csv('test.csv',sep='|')

for line in range(len(partial_table_fans['tempo'])):
  time = partial_table_fans['tempo'][line][0:10]
  date_time_obj = datetime.strptime(time, '%Y-%m-%d')
  date_time_obj = date_time_obj + timedelta(hours=-8)
  partial_table_fans['tempo'][line] = date_time_obj
partial_table_fans

df = partial_table_fans.loc[partial_table_fans['business_id'] == '830710710444743']
df = df.loc[df['info'] == 'country']
df = df.loc[df['dimensions'] == 'BR']
df